### ISSUE TITLE
hey can some one help me to add some fixing and explaining pls !

### ISSUE THREAD

**Issue by qwedaTrr231** [in-future-world/Real_Python#2]
#the code
def myFirstFunc():
global userName =["dani","yoni","yaniv","amir","lor","asaf","tele","gala","tali","shira"]:
 for x = in userName:
 print (x)
if x = "amir":
 print("you are the developer") 
else
print("normal user") 

def LifeStatusFunc():
global lifeStatus = ("single","parntered")
for x in lifeStatus: 
print(x)
for x == "shira":
brake
myFirstFunc()
lifeStatusFunc()
print(lifeStatus.userName)

#iwant printage of userName with lifeStatus of eatch name in the userNameList thank you !!!

**Comment by in-future-world** [comment]
Hello,
You have many errors in your Code.
Below the code is your answers.

dict = {"dani":"single",
        "yoni":"parent",
        "amir":"marriage",
        "shira":"single"
        }
username_input = input("Enter Username: ")
print(username_input,"are",dict[username_input])

Only add persons in this format 
"prant":"single",

**Comment by qwedaTrr231** [comment]
thank you !!! ill' keep learning.

real_python can help me learn with practice ? I'd opend some game code its look too complicated for me for now.
can you advice me bro ?

**Comment by in-future-world** [comment]
If you want any help, related to anything in computer.
Contact me using my email or WhatsApp - 
info@infutureworld.xyz 
https://wa.me/message/RJSMU4K3QDHZC1

This is my advice.🙃
So Close this issue...
